import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.database import db

client = TestClient(app)

def test_seed_endpoint():
    response = client.post("/api/dev/seed")
    assert response.status_code in (200, 201)
    claims = response.json()
    assert len(claims) == 20

    fraud_claims = [c for c in claims if c["true_label"] is True]
    legit_claims = [c for c in claims if c["true_label"] is False]
    unlabeled_claims = [c for c in claims if c["true_label"] is None]

    assert len(fraud_claims) == 7
    assert len(legit_claims) == 7
    assert len(unlabeled_claims) == 6

    # Verify each claim has risk score and explanations generated by ML model
    for claim in claims:
        assert "fraud_score" in claim
        assert 0.0 <= claim["fraud_score"] <= 1.0
        assert claim["risk_level"] in ("low", "medium", "high")
        assert "explanations" in claim

def test_model_performance_after_seeding():
    client.post("/api/dev/seed")
    perf_resp = client.get("/api/analytics/model-performance")
    assert perf_resp.status_code == 200
    perf = perf_resp.json()

    assert perf["total_labeled"] == 14
    assert perf["accuracy"] is not None
    assert perf["precision"] is not None
    assert perf["recall"] is not None
    assert perf["f1_score"] is not None
    assert perf["roc_auc"] is not None

    # Check metrics are valid numbers between 0.0 and 1.0
    for metric in ("accuracy", "precision", "recall", "f1_score", "roc_auc"):
        val = perf[metric]
        assert isinstance(val, float)
        assert 0.0 <= val <= 1.0

    cm = perf["confusion_matrix"]
    assert cm["tp"] + cm["fp"] + cm["tn"] + cm["fn"] == 14
